```{r libraries, include=FALSE}
library(dplyr)
```

# 주소 데이터 불러오기

```{r}
pathPrefix = '../cleaned/'
YYYYMMPrefix = '202004/'
pathPostFix = 'JiBeon_Korea.csv'
path = paste0(pathPrefix, YYYYMMPrefix, pathPostFix)
df = read.csv(path, fileEncoding = 'UTF-8')

head(df)
```

### 모든 컬럼의 타입을 chraracter로 변경하기
```{r }
df$BeopJeongDongKoDeu = as.character(df$BeopJeongDongKoDeu) # 법정동코드 10자리 , 앞 두자리는 시도, 3~5자리는 구
df$SiDoMyeong = as.character(df$SiDoMyeong) #시, 도
df$SiGunGuMyeong = as.character(df$SiGunGuMyeong) #구
df$BeopJeongEupMyeonDongMyeong = as.character(df$BeopJeongEupMyeonDongMyeong) #동
df$JiBeonBonBeon = as.character(df$JiBeonBonBeon.BeonJi) #지번본번
df$JiBeonBuBeon = as.character(df$JiBeonBuBeon.Ho) #지번부번

head(df)
```

## 코드,시,군,동, 번지만 분리하여 데이터 프레임 생성

```{r}
KAAreas = c('SiDoMyeong', 'SiGunGuMyeong', 'BeopJeongEupMyeonDongMyeong','JiBeonBonBeon','JiBeonBuBeon')
columns = c('BeopJeongDongKoDeu', KAAreas)

df2 <- df[KAAreas]
#df2 <- df[columns]

head(df2)

```



```{r  }
df2$fullAddress <- paste(df2$SiDoMyeong, df2$SiGunGuMyeong, df2$BeopJeongEupMyeonDongMyeong, df2$JiBeonBonBeon, df2$JiBeonBuBeon)
head(df2)

df_combined <- data.frame(df2$fullAddress)
# 
head(df_combined)

```


```{r create a clean data}
pathPrefix = '../cleaned/'
pathPostFix = 'cleaned_file.csv'
path = paste0(pathPrefix, pathPostFix)


write.csv(df_combined, path, row.names = FALSE, fileEncoding = 'UTF-8')
#save(df_combined, file = path)
```

```{r  }
df_cleaned <- read.csv("../cleaned/cleaned_file.csv",fileEncoding = 'UTF-8')
#


head(df_cleaned)

```


```{r read a cleaned file}



```

